### ISSUE TITLE
[Command Bug] negaverse steals normal/rare/epic items

### ISSUE THREAD

**Issue by jackpoz** [aikaterna/gobcog#449]
## Complete these first
- [x] I confirm that I am the owner of the bot running Adventure.
- [x] I confirm that I have not modified the source code of Adventure.
- [ ] I'm an Adventure user but not the bot owner.
- [x] I confirm that I have checked the [issue tracker](../) and this bug hasn't been reported already.

## Command name

negaverse

## Expected Behavior
negaverse shouldn't steal normal/rare/epic items stored in the backpack

## Current Behavior
normal/rare/epic items are stolen from the backpack when using negaverse command. This started to happen some months ago, it wasn't always like that

Adventure version: 4.0.4
Repo: https://github.com/aikaterna/gobcog.git
Commit: 4823374f48d4e2d74a01049cfd2eb77791464a39

## Possible Solution
https://github.com/aikaterna/gobcog/blob/4823374f48d4e2d74a01049cfd2eb77791464a39/adventure/negaverse.py#L219 specifies the exclude parameter with strings, but https://github.com/aikaterna/gobcog/blob/4823374f48d4e2d74a01049cfd2eb77791464a39/adventure/charsheet.py#L732-L734 then mixes a bit of strings and enums. Not sure if this mismatch can cause issues, with the code checking rarety comparing wrong values.

## Steps to Reproduce
1. "loot normal" and store at least 1 normal item in the backpack
2. "negaverse" going all in with all the gold and lose. The "lose" part might require a few tries
3. Notice how the normal item will be stolen

## Context (Environment)
This is an unexpected behavior as I played for years with normal items in the backpack without them being stolen

**Comment by aikaterna** [comment]
This is intended.

**Comment by jackpoz** [comment]
What's the point of `exclude={"event", "normal", "rare", "epic"}` then if no items are excluded ?

**Comment by aikaterna** [comment]
Someone can check it out when they have time, moving a reference to the tracker

**Comment by jackpoz** [comment]
I opened a PR fixing the issue

**Comment by jackpoz** [comment]
this is actually happening again
![image](https://github.com/aikaterna/gobcog/assets/1153754/3f37757f-ed52-4e8a-ad8e-712bcfac3f85)
![image](https://github.com/aikaterna/gobcog/assets/1153754/2e8f4877-39c0-46fc-b126-18e39a7d6681)

**Comment by jackpoz** [comment]
Ah well, it seems to be the new behavior with f28512e4dae27653221ba37aa990e1f82e10a3a0
